# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, code: int=None, data: str=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param code: The code of this InlineResponse200.  # noqa: E501
        :type code: int
        :param data: The data of this InlineResponse200.  # noqa: E501
        :type data: str
        """
        self.swagger_types = {
            'code': int,
            'data': str
        }

        self.attribute_map = {
            'code': 'code',
            'data': 'data'
        }

        self._code = code
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> int:
        """Gets the code of this InlineResponse200.


        :return: The code of this InlineResponse200.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code: int):
        """Sets the code of this InlineResponse200.


        :param code: The code of this InlineResponse200.
        :type code: int
        """

        self._code = code

    @property
    def data(self) -> str:
        """Gets the data of this InlineResponse200.


        :return: The data of this InlineResponse200.
        :rtype: str
        """
        return self._data

    @data.setter
    def data(self, data: str):
        """Sets the data of this InlineResponse200.


        :param data: The data of this InlineResponse200.
        :type data: str
        """

        self._data = data
