# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.mi_response_response_directives_audio_item_stream import MiResponseResponseDirectivesAudioItemStream  # noqa: F401,E501
from swagger_server import util


class MiResponseResponseDirectivesAudioItem(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, stream: MiResponseResponseDirectivesAudioItemStream=None):  # noqa: E501
        """MiResponseResponseDirectivesAudioItem - a model defined in Swagger

        :param stream: The stream of this MiResponseResponseDirectivesAudioItem.  # noqa: E501
        :type stream: MiResponseResponseDirectivesAudioItemStream
        """
        self.swagger_types = {
            'stream': MiResponseResponseDirectivesAudioItemStream
        }

        self.attribute_map = {
            'stream': 'stream'
        }

        self._stream = stream

    @classmethod
    def from_dict(cls, dikt) -> 'MiResponseResponseDirectivesAudioItem':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MiResponse_response_directives_audio_item of this MiResponseResponseDirectivesAudioItem.  # noqa: E501
        :rtype: MiResponseResponseDirectivesAudioItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def stream(self) -> MiResponseResponseDirectivesAudioItemStream:
        """Gets the stream of this MiResponseResponseDirectivesAudioItem.


        :return: The stream of this MiResponseResponseDirectivesAudioItem.
        :rtype: MiResponseResponseDirectivesAudioItemStream
        """
        return self._stream

    @stream.setter
    def stream(self, stream: MiResponseResponseDirectivesAudioItemStream):
        """Sets the stream of this MiResponseResponseDirectivesAudioItem.


        :param stream: The stream of this MiResponseResponseDirectivesAudioItem.
        :type stream: MiResponseResponseDirectivesAudioItemStream
        """

        self._stream = stream
