# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class MiRequestSessionUser(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, user_id: str=None, access_token: str=None):  # noqa: E501
        """MiRequestSessionUser - a model defined in Swagger

        :param user_id: The user_id of this MiRequestSessionUser.  # noqa: E501
        :type user_id: str
        :param access_token: The access_token of this MiRequestSessionUser.  # noqa: E501
        :type access_token: str
        """
        self.swagger_types = {
            'user_id': str,
            'access_token': str
        }

        self.attribute_map = {
            'user_id': 'user_id',
            'access_token': 'access_token'
        }

        self._user_id = user_id
        self._access_token = access_token

    @classmethod
    def from_dict(cls, dikt) -> 'MiRequestSessionUser':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MiRequest_session_user of this MiRequestSessionUser.  # noqa: E501
        :rtype: MiRequestSessionUser
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_id(self) -> str:
        """Gets the user_id of this MiRequestSessionUser.


        :return: The user_id of this MiRequestSessionUser.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: str):
        """Sets the user_id of this MiRequestSessionUser.


        :param user_id: The user_id of this MiRequestSessionUser.
        :type user_id: str
        """

        self._user_id = user_id

    @property
    def access_token(self) -> str:
        """Gets the access_token of this MiRequestSessionUser.


        :return: The access_token of this MiRequestSessionUser.
        :rtype: str
        """
        return self._access_token

    @access_token.setter
    def access_token(self, access_token: str):
        """Sets the access_token of this MiRequestSessionUser.


        :param access_token: The access_token of this MiRequestSessionUser.
        :type access_token: str
        """

        self._access_token = access_token
