# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class MiResponseResponseToDisplayUiTemplateItems(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, image_style: str=None, images: object=None, intent: str=None, title: str=None, logo: str=None):  # noqa: E501
        """MiResponseResponseToDisplayUiTemplateItems - a model defined in Swagger

        :param image_style: The image_style of this MiResponseResponseToDisplayUiTemplateItems.  # noqa: E501
        :type image_style: str
        :param images: The images of this MiResponseResponseToDisplayUiTemplateItems.  # noqa: E501
        :type images: object
        :param intent: The intent of this MiResponseResponseToDisplayUiTemplateItems.  # noqa: E501
        :type intent: str
        :param title: The title of this MiResponseResponseToDisplayUiTemplateItems.  # noqa: E501
        :type title: str
        :param logo: The logo of this MiResponseResponseToDisplayUiTemplateItems.  # noqa: E501
        :type logo: str
        """
        self.swagger_types = {
            'image_style': str,
            'images': object,
            'intent': str,
            'title': str,
            'logo': str
        }

        self.attribute_map = {
            'image_style': 'image_style',
            'images': 'images',
            'intent': 'intent',
            'title': 'title',
            'logo': 'logo'
        }

        self._image_style = image_style
        self._images = images
        self._intent = intent
        self._title = title
        self._logo = logo

    @classmethod
    def from_dict(cls, dikt) -> 'MiResponseResponseToDisplayUiTemplateItems':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MiResponse_response_to_display_ui_template_items of this MiResponseResponseToDisplayUiTemplateItems.  # noqa: E501
        :rtype: MiResponseResponseToDisplayUiTemplateItems
        """
        return util.deserialize_model(dikt, cls)

    @property
    def image_style(self) -> str:
        """Gets the image_style of this MiResponseResponseToDisplayUiTemplateItems.


        :return: The image_style of this MiResponseResponseToDisplayUiTemplateItems.
        :rtype: str
        """
        return self._image_style

    @image_style.setter
    def image_style(self, image_style: str):
        """Sets the image_style of this MiResponseResponseToDisplayUiTemplateItems.


        :param image_style: The image_style of this MiResponseResponseToDisplayUiTemplateItems.
        :type image_style: str
        """

        self._image_style = image_style

    @property
    def images(self) -> object:
        """Gets the images of this MiResponseResponseToDisplayUiTemplateItems.


        :return: The images of this MiResponseResponseToDisplayUiTemplateItems.
        :rtype: object
        """
        return self._images

    @images.setter
    def images(self, images: object):
        """Sets the images of this MiResponseResponseToDisplayUiTemplateItems.


        :param images: The images of this MiResponseResponseToDisplayUiTemplateItems.
        :type images: object
        """

        self._images = images

    @property
    def intent(self) -> str:
        """Gets the intent of this MiResponseResponseToDisplayUiTemplateItems.


        :return: The intent of this MiResponseResponseToDisplayUiTemplateItems.
        :rtype: str
        """
        return self._intent

    @intent.setter
    def intent(self, intent: str):
        """Sets the intent of this MiResponseResponseToDisplayUiTemplateItems.


        :param intent: The intent of this MiResponseResponseToDisplayUiTemplateItems.
        :type intent: str
        """

        self._intent = intent

    @property
    def title(self) -> str:
        """Gets the title of this MiResponseResponseToDisplayUiTemplateItems.


        :return: The title of this MiResponseResponseToDisplayUiTemplateItems.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this MiResponseResponseToDisplayUiTemplateItems.


        :param title: The title of this MiResponseResponseToDisplayUiTemplateItems.
        :type title: str
        """

        self._title = title

    @property
    def logo(self) -> str:
        """Gets the logo of this MiResponseResponseToDisplayUiTemplateItems.


        :return: The logo of this MiResponseResponseToDisplayUiTemplateItems.
        :rtype: str
        """
        return self._logo

    @logo.setter
    def logo(self, logo: str):
        """Sets the logo of this MiResponseResponseToDisplayUiTemplateItems.


        :param logo: The logo of this MiResponseResponseToDisplayUiTemplateItems.
        :type logo: str
        """

        self._logo = logo
