# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class MiResponseResponseToDisplayUiTemplateItem(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, image_style: str=None, images: object=None, intent: str=None, title: str=None, body: object=None, background_image: str=None):  # noqa: E501
        """MiResponseResponseToDisplayUiTemplateItem - a model defined in Swagger

        :param image_style: The image_style of this MiResponseResponseToDisplayUiTemplateItem.  # noqa: E501
        :type image_style: str
        :param images: The images of this MiResponseResponseToDisplayUiTemplateItem.  # noqa: E501
        :type images: object
        :param intent: The intent of this MiResponseResponseToDisplayUiTemplateItem.  # noqa: E501
        :type intent: str
        :param title: The title of this MiResponseResponseToDisplayUiTemplateItem.  # noqa: E501
        :type title: str
        :param body: The body of this MiResponseResponseToDisplayUiTemplateItem.  # noqa: E501
        :type body: object
        :param background_image: The background_image of this MiResponseResponseToDisplayUiTemplateItem.  # noqa: E501
        :type background_image: str
        """
        self.swagger_types = {
            'image_style': str,
            'images': object,
            'intent': str,
            'title': str,
            'body': object,
            'background_image': str
        }

        self.attribute_map = {
            'image_style': 'image_style',
            'images': 'images',
            'intent': 'intent',
            'title': 'title',
            'body': 'body',
            'background_image': 'background_image'
        }

        self._image_style = image_style
        self._images = images
        self._intent = intent
        self._title = title
        self._body = body
        self._background_image = background_image

    @classmethod
    def from_dict(cls, dikt) -> 'MiResponseResponseToDisplayUiTemplateItem':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MiResponse_response_to_display_ui_template_item of this MiResponseResponseToDisplayUiTemplateItem.  # noqa: E501
        :rtype: MiResponseResponseToDisplayUiTemplateItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def image_style(self) -> str:
        """Gets the image_style of this MiResponseResponseToDisplayUiTemplateItem.


        :return: The image_style of this MiResponseResponseToDisplayUiTemplateItem.
        :rtype: str
        """
        return self._image_style

    @image_style.setter
    def image_style(self, image_style: str):
        """Sets the image_style of this MiResponseResponseToDisplayUiTemplateItem.


        :param image_style: The image_style of this MiResponseResponseToDisplayUiTemplateItem.
        :type image_style: str
        """

        self._image_style = image_style

    @property
    def images(self) -> object:
        """Gets the images of this MiResponseResponseToDisplayUiTemplateItem.


        :return: The images of this MiResponseResponseToDisplayUiTemplateItem.
        :rtype: object
        """
        return self._images

    @images.setter
    def images(self, images: object):
        """Sets the images of this MiResponseResponseToDisplayUiTemplateItem.


        :param images: The images of this MiResponseResponseToDisplayUiTemplateItem.
        :type images: object
        """

        self._images = images

    @property
    def intent(self) -> str:
        """Gets the intent of this MiResponseResponseToDisplayUiTemplateItem.


        :return: The intent of this MiResponseResponseToDisplayUiTemplateItem.
        :rtype: str
        """
        return self._intent

    @intent.setter
    def intent(self, intent: str):
        """Sets the intent of this MiResponseResponseToDisplayUiTemplateItem.


        :param intent: The intent of this MiResponseResponseToDisplayUiTemplateItem.
        :type intent: str
        """

        self._intent = intent

    @property
    def title(self) -> str:
        """Gets the title of this MiResponseResponseToDisplayUiTemplateItem.


        :return: The title of this MiResponseResponseToDisplayUiTemplateItem.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this MiResponseResponseToDisplayUiTemplateItem.


        :param title: The title of this MiResponseResponseToDisplayUiTemplateItem.
        :type title: str
        """

        self._title = title

    @property
    def body(self) -> object:
        """Gets the body of this MiResponseResponseToDisplayUiTemplateItem.


        :return: The body of this MiResponseResponseToDisplayUiTemplateItem.
        :rtype: object
        """
        return self._body

    @body.setter
    def body(self, body: object):
        """Sets the body of this MiResponseResponseToDisplayUiTemplateItem.


        :param body: The body of this MiResponseResponseToDisplayUiTemplateItem.
        :type body: object
        """

        self._body = body

    @property
    def background_image(self) -> str:
        """Gets the background_image of this MiResponseResponseToDisplayUiTemplateItem.


        :return: The background_image of this MiResponseResponseToDisplayUiTemplateItem.
        :rtype: str
        """
        return self._background_image

    @background_image.setter
    def background_image(self, background_image: str):
        """Sets the background_image of this MiResponseResponseToDisplayUiTemplateItem.


        :param background_image: The background_image of this MiResponseResponseToDisplayUiTemplateItem.
        :type background_image: str
        """

        self._background_image = background_image
